name: Check JKS Certificate Expiry

on:
  workflow_dispatch:

jobs:
  check-jks-expiry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Decode Keystore from Secret
        run: |
          # Recreate the JKS file from the Base64 encoded secret
          echo "${{ secrets.JKS_FILE_B64 }}" | base64 --decode > mykeystore.jks

      - name: List certificates and show expiry date
        run: |
          # Use the secret for the password and reference the newly created file
          keytool -list -v -keystore mykeystore.jks -storepass "${{ secrets.JKS_PASSWORD }}" | grep "until:"
