name: Check JKS Certificate Expiry

on:
  workflow_dispatch:
 

jobs:
  check-jks-expiry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List certificates in JKS and show expiry
        run: |
          KEYSTORE_FILE="mykeystore.jks"
          KEYSTORE_PASS="mykeypassword"
          keytool -list -v -keystore "$KEYSTORE_FILE" -storepass "$KEYSTORE_PASS" | grep -E 'Alias name|Valid from'
